<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>kewarganegaraan</name>
   <tag></tag>
   <elementGuidId>6f939574-0466-489f-a020-459def36ffca</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>/*[@id=&quot;q-app&quot;]/div/div[2]/main/div/div/div[2]/div/div/div/div/form/label[1]/div/div[1]/div[1]/div[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/*[@id=&quot;q-app&quot;]/div/div[2]/main/div/div/div[2]/div/div/div/div/form/label[1]/div/div[1]/div[1]/div[1]</value>
   </webElementProperties>
</WebElementEntity>
