<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>pilih_kewarganegaraan</name>
   <tag></tag>
   <elementGuidId>a99e790b-a6fa-4c39-9e89-29d6e2267e29</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//select/option[@value='${Negara}']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//select/option[@value='${Negara}']</value>
   </webElementProperties>
</WebElementEntity>
