<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>tulisan_search_cif</name>
   <tag></tag>
   <elementGuidId>e0108c0a-e851-469c-94f9-f981b340ec19</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;q-app&quot;]/div/div[2]/div/div/div[1]/div/div[3]/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;q-app&quot;]/div/div[2]/div/div/div[1]/div/div[3]/div</value>
   </webElementProperties>
</WebElementEntity>
